In [1]:
import pandas as pd
import numpy as np
from assignta import AssignTa


def test1():
    a = AssignTa()
    a.assign_ta_df("assignta_data/tas.csv")
    a.assign_lab_df("assignta_data/sections.csv")
    a.assignment = pd.read_csv("assignta_data/test1.csv", header=None).to_numpy()
    # TODO make a setup with a known assignment matrix
    return a


def main():
    test = test1()
    print(test.assignment)
    print(f"Test 1 dtype: {test.assignment.dtype}")



main()

[[0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 1]
 [0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
 [0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0]
 [0 1 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0]
 [0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1]
 [1 1 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 1 0 0 0 0 0 0 1 0 0 0]
 [0 0 0 1 0 0 0 1 0 0 1 1 0 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0]
 [0 0 0 1 0 1 0 1 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 1 0 0 0 0 0 1 0 1 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 

In [2]:
def get_conflict_pairs(test, assignment: np.array) -> list:
    all_conflicts = []
    all_lab_times = test.lab["daytime"].values  # Direct numpy array from pandas
    ta_indices, lab_indices = np.where(assignment == 1)
    assigned_times = all_lab_times[lab_indices]
    for ta_idx in np.unique(ta_indices):
        ta_mask = ta_indices == ta_idx
        ta_labs = lab_indices[ta_mask]
        ta_times = assigned_times[ta_mask]
        unique_times, inverse, counts = np.unique(ta_times, return_inverse=True, return_counts=True)
        conflicting_time_mask = counts > 1
        if not conflicting_time_mask.any():
            continue
        for time_idx in np.where(conflicting_time_mask)[0]:
            conflict_mask = inverse == time_idx
            conflicting_labs = ta_labs[conflict_mask]
            conflict_locations = [(ta_idx, lab_idx) for lab_idx in conflicting_labs]
            all_conflicts.extend(conflict_locations)
    return all_conflicts

def test1():
    a = AssignTa()
    a.assign_ta_df("assignta_data/tas.csv")
    a.assign_lab_df("assignta_data/sections.csv")
    a.assignment = pd.read_csv("assignta_data/test1.csv", header=None).to_numpy()
    # TODO make a setup with a known assignment matrix
    return a

test = test1()
print(test.assignment)
conflicts = get_conflict_pairs(test, test.assignment)
all_lab_times = test.lab["daytime"].values
for ta_idx, lab_idx in conflicts:
    print(f"TA {ta_idx}, Lab {lab_idx}: {all_lab_times[lab_idx]}, assignment value: {test.assignment[ta_idx, lab_idx]}")

[[0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 1]
 [0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
 [0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0]
 [0 1 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0]
 [0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1]
 [1 1 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 1 0 0 0 0 0 0 1 0 0 0]
 [0 0 0 1 0 0 0 1 0 0 1 1 0 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0]
 [0 0 0 1 0 1 0 1 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 1 0 0 0 0 0 1 0 1 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 

In [3]:
# Debug - check all lab times
for i in range(17):
    print(f"Lab {i}: {test.lab['daytime'].iloc[i]}")

Lab 0: R 1145-125
Lab 1: W 950-1130
Lab 2: W 950-1130
Lab 3: W 950-1130
Lab 4: W 1145-125
Lab 5: W 1145-125
Lab 6: W 250-430
Lab 7: W 250-430
Lab 8: W 250-430
Lab 9: W 440-630
Lab 10: R 950-1130
Lab 11: R 950-1130
Lab 12: R 1145-125
Lab 13: R 1145-125
Lab 14: R 1145-125
Lab 15: R 250-430
Lab 16: R 250-430


In [4]:
conflicts

[(0, 15),
 (0, 16),
 (4, 6),
 (4, 7),
 (14, 0),
 (14, 12),
 (14, 13),
 (17, 10),
 (17, 11),
 (20, 10),
 (20, 11),
 (24, 6),
 (24, 8),
 (38, 13),
 (38, 14)]

In [6]:
test = test1()
first = test.assignment
second = test.undersupport_agent(test.assignment)
print(f"Undersupport score: matrix 1: {first}, matrix 2: {second} ")


TypeError: 'NoneType' object is not subscriptable